apiVersion: v2
name: store-chart
description: A Helm chart for Urumi Stores
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: wordpress
    version: 23.0.7
    repository: https://charts.bitnami.com/bitnami
    alias: store